import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  corePlugins: { preflight: false },
  theme: {
    extend: {
      colors: {
        // Ocean Depth — teal/coral brand
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'primary-soft': 'var(--primary-soft)',
        'primary-container': 'var(--brand-soft)',
        'on-primary': 'var(--fg-on-brand)',
        'primary-fixed': 'var(--brand-soft)',
        'primary-fixed-dim': 'var(--bg-hover)',
        accent: 'var(--accent)',
        'accent-soft': 'var(--accent-soft)',
        gold: 'var(--fg-warning)',
        'gold-soft': 'var(--color-warning-100)',
        'gold-faint': 'var(--color-warning-100)',
        admin: 'var(--accent)',
        'admin-soft': 'var(--color-accent-100)',
        secondary: 'var(--fg-muted)',
        'secondary-container': 'var(--bg-subtle)',
        'on-secondary-container': 'var(--fg-heading)',
        tertiary: 'var(--fg-subtle)',
        'tertiary-container': 'var(--bg-subtle)',
        'on-tertiary-container': 'var(--fg-heading)',
        error: 'var(--fg-danger)',
        'on-error': 'var(--fg-on-brand)',
        'error-container': 'var(--color-danger-100)',
        surface: 'var(--bg-surface)',
        'surface-dim': 'var(--bg-hover)',
        'surface-bright': 'var(--bg-surface)',
        'surface-container-lowest': 'var(--bg-surface)',
        'surface-container-low': 'var(--bg-subtle)',
        'surface-container': 'var(--bg-subtle)',
        'surface-container-high': 'var(--bg-hover)',
        'surface-container-highest': 'var(--border-strong)',
        'surface-variant': 'var(--bg-subtle)',
        'on-surface': 'var(--fg-body)',
        'on-surface-variant': 'var(--fg-muted)',
        outline: 'var(--fg-subtle)',
        'outline-variant': 'var(--border)',
        'inverse-surface': 'var(--fg-heading)',
        'inverse-on-surface': 'var(--bg-surface)',
        'inverse-primary': 'var(--primary)',
        background: 'var(--bg-app)',
        'on-background': 'var(--fg-heading)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius-md)',
        sm: 'var(--radius-sm)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-pill)',
      },
      spacing: {
        'input-sm': '36px',
        'input-md': '44px',
        'input-lg': '52px',
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['"Inter"', 'system-ui', 'sans-serif'],
        label: ['"Inter"', 'system-ui', 'sans-serif'],
        arabic: ['"Cairo"', '"Readex Pro"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'SFMono-Regular', 'Consolas', 'Menlo', 'monospace'],
        sans: ['"Inter"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        '2xs': 'var(--text-2xs)',
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        md: 'var(--text-md)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        glow: 'var(--ring-focus)',
        'glow-danger': '0 0 0 3px rgba(239, 68, 68, 0.25)',
        brand: 'var(--shadow-brand)',
      },
    },
  },
  plugins: [forms, containerQueries],
}
